"""
src/email_sender.py
===================
Sends a daily digest email summarising the top-ranked job postings using the
Resend API (https://resend.com).

The email includes:
* A ranked HTML table of the top N jobs
* Score + reasoning per job
* Apply link
* Per-job ATS keyword suggestions (if available)
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

import resend

logger = logging.getLogger(__name__)


def _get_resend_key() -> str:
    key = os.environ.get("RESEND_API_KEY")
    if not key:
        raise EnvironmentError("RESEND_API_KEY environment variable is not set.")
    return key


# ──────────────────────────────────────────────────────────────────────────────
# HTML email builder
# ──────────────────────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
  .container {{ max-width: 700px; margin: auto; background: #fff; padding: 24px;
               border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,.1); }}
  h1 {{ color: #2c3e50; font-size: 22px; }}
  h2 {{ color: #34495e; font-size: 16px; margin: 0 0 4px; }}
  .job {{ border: 1px solid #e0e0e0; border-radius: 6px; padding: 16px;
          margin-bottom: 16px; }}
  .score {{ display: inline-block; padding: 3px 10px; border-radius: 12px;
            font-weight: bold; font-size: 13px; color: #fff; }}
  .score-high {{ background: #27ae60; }}
  .score-mid  {{ background: #f39c12; }}
  .score-low  {{ background: #e74c3c; }}
  .meta {{ color: #666; font-size: 13px; margin: 4px 0 8px; }}
  .reasoning {{ font-style: italic; color: #555; font-size: 13px; }}
  .ats {{ background: #eef4ff; border-left: 3px solid #3498db; padding: 6px 10px;
          font-size: 12px; margin-top: 8px; border-radius: 0 4px 4px 0; }}
  .apply-btn {{ display: inline-block; margin-top: 10px; padding: 7px 16px;
               background: #2980b9; color: #fff; text-decoration: none;
               border-radius: 4px; font-size: 13px; }}
  .footer {{ margin-top: 24px; font-size: 11px; color: #aaa; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <h1>🔍 Daily Job Digest — {date}</h1>
  <p>Here are your top <strong>{count}</strong> job matches for today.</p>
  {jobs_html}
  <div class="footer">Generated by your AI Job Search System · <a href="#">Unsubscribe</a></div>
</div>
</body>
</html>
"""

_JOB_BLOCK = """\
<div class="job">
  <h2>{rank}. {title} — {company}</h2>
  <div class="meta">📍 {location} &nbsp;|&nbsp; 🗂 {source} &nbsp;|&nbsp;
    <span class="score {score_class}">{score}/10</span></div>
  <p class="reasoning">💡 {reasoning}</p>
  {ats_block}
  <a class="apply-btn" href="{url}" target="_blank">View &amp; Apply →</a>
</div>
"""

_ATS_BLOCK = """\
<div class="ats">
  <strong>ATS keywords to add:</strong> {keywords}
</div>
"""


def _score_class(score: float) -> str:
    if score >= 8:
        return "score-high"
    if score >= 6:
        return "score-mid"
    return "score-low"


def _build_html(jobs: list[dict[str, Any]], run_date: str) -> str:
    blocks: list[str] = []
    for i, job in enumerate(jobs, start=1):
        score = job.get("score", 0.0)
        ats_keywords: list[str] = job.get("ats_keywords", [])
        ats_block = (
            _ATS_BLOCK.format(keywords=", ".join(ats_keywords))
            if ats_keywords
            else ""
        )
        blocks.append(
            _JOB_BLOCK.format(
                rank=i,
                title=job.get("title", ""),
                company=job.get("company", ""),
                location=job.get("location", ""),
                source=job.get("source", ""),
                score=f"{score:.1f}",
                score_class=_score_class(score),
                reasoning=job.get("reasoning", ""),
                ats_block=ats_block,
                url=job.get("url", "#"),
            )
        )
    return _HTML_TEMPLATE.format(
        date=run_date,
        count=len(jobs),
        jobs_html="\n".join(blocks),
    )


def _build_plain_text(jobs: list[dict[str, Any]], run_date: str) -> str:
    lines: list[str] = [
        f"Daily Job Digest — {run_date}",
        "=" * 50,
        "",
    ]
    for i, job in enumerate(jobs, start=1):
        score = job.get("score", 0.0)
        lines += [
            f"{i}. {job.get('title', '')} @ {job.get('company', '')}",
            f"   Location : {job.get('location', '')}",
            f"   Score    : {score:.1f}/10",
            f"   Reason   : {job.get('reasoning', '')}",
            f"   Apply    : {job.get('url', '')}",
            "",
        ]
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def send_digest(
    jobs: list[dict[str, Any]],
    to_email: str,
    from_email: str = "jobs@updates.example.com",
    run_date: str | None = None,
) -> str:
    """
    Send the daily job digest to *to_email* via Resend.

    Parameters
    ----------
    jobs:
        Ranked job list (from ``ranker.rank_jobs``), already sliced to top N.
    to_email:
        Recipient email address.
    from_email:
        Sender address (must be a verified Resend domain).
    run_date:
        Human-readable date string (defaults to today).

    Returns
    -------
    str
        Resend message ID.
    """
    from datetime import date as _date

    if run_date is None:
        run_date = _date.today().strftime("%B %d, %Y")

    resend.api_key = _get_resend_key()

    html = _build_html(jobs, run_date)
    text = _build_plain_text(jobs, run_date)

    params: resend.Emails.SendParams = {
        "from": from_email,
        "to": [to_email],
        "subject": f"🔍 Job Digest — {run_date} ({len(jobs)} matches)",
        "html": html,
        "text": text,
    }
    response = resend.Emails.send(params)
    msg_id: str = response["id"]
    logger.info("Digest sent to %s (message ID: %s)", to_email, msg_id)
    return msg_id
